---
# Runs an ansible role
# Usage:
#
# ansible-playbook -i inventories/example/hosts -u <user> -K -v ./run_role.yml <-l mservice> -e role=my_awesome_role
#
- hosts: all
  become: True
  gather_facts: False
  roles:
    - "{{ role }}"