---
# Runs an ansible role
# Usage:
#   ansible-playbook ./run_role.yml -u admin-user -i inventory/hosts -e role=my_awesome_role
#
- hosts: all
  become: True
  gather_facts: False
  roles:
    - "{{ role }}"