---
#
# Run  update playbook in existing host
#
# Usage:
#
#ansible-playbook -i inventories/example/hosts -u <user> -K -v ./update-host.yml < -l host group>
#

- hosts: all
  become: yes
  roles:
     - common
     - timezone
     - locale
     - sysctl
     - postfix-relay
     - security
     - firewall
     - sshd