---
#
# Run users and sudo role
#
# Usage:
# ansible-playbook -i inventories/example/hosts -u <user> -K -v ./users.yml < -l host group>
#

- hosts: all
  become: yes

  roles:
     - users
     - sudo