---
# Tasks for java role

- name: 'Install Java JRE {{  java_jre_version }}'
  apt: 
    name: openjdk-{{ java_jre_version }}-jre-headless
    state: present

- name: Set JAVA_HOME.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home