---
#
# Common role
#
# Tasks for common role
#

- name: Install common system packages
  apt:
    name: "{{ item }}"
    install_recommends: yes
    state: present 
    update_cache: yes
  with_items: "{{ common_pkgs }}"