---
#
# Users role
#
# Default variables for users role
#
# Encode user password
#
# pip install passlib
#
# python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"
#
# http://docs.ansible.com/ansible/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module
#
users_purge: []
users_extra: []

# add default admin group
users_group: [admin]

# password = empty-password
root_passwd: $6$/LjEY1ZOa8D$b3uVy/38WPBr.K7Gib3TyzJJU9ZjMuJyBLy7UYYZ9nw1Jon2PG8YCYHi8WhpgcKOOMY1RI.Q2iCrHNWb9AjdS1

# admin users
users:
  admin: # admin groups
    - name: 'admin-user'
      # passwd = qwert-11
      passwd: $6$qtzv48Uk$3hRmaE.N9i1Byf/lj0wbX/0VrTzM.Ms.4Q0ifauywEUobP2DKa9h8iZGz0Dn3q4hOpp5AfT0d1EQCtk88WVG70
      groups: ['admin','adm']
      authorized_keys:
        - admin-user