---
#
# Timezone role
#
# Tasks that set timezone for host
#

- name: Set /etc/localtime to {{ timezone }}
  copy: src=/usr/share/zoneinfo/{{ timezone }}
        dest=/etc/localtime
        owner=root
        group=root
        mode=0644
        backup=yes
        
- name: Set /etc/timezone to {{ timezone }}
  template: dest=/etc/timezone src=timezone.j2
  notify: update tzdata